cc_binary(
        name = "1",
        srcs = ["1.cc"],
)

cc_binary(
        name = "2_unopt",
        srcs = ["2.cc"],
        copts = ["-O0"],
)

cc_binary(
        name = "2_opt",
        srcs = ["2.cc"],
        copts = ["-O3"],
)

cc_binary(
        name = "3",
        srcs = ["3.cc"],
)
