cc_binary(
        name = "5",
        srcs = ["5.cc"],
)

cc_binary(
        name = "6",
        srcs = ["6.cc"],
)

cc_binary(
        name = "7",
        srcs = ["7.cc"],
)

cc_binary(
        name = "8",
        srcs = ["8.cc"],
)

cc_binary(
        name = "9",
        srcs = ["9.cc"],
)
